Server commands
Sinan-Karakaya/Zappy pull request #18
Opened 2023-06-16 14:43 UTC by JasonLAGOUTE

## **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [X] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR introduces the following:
- Final server of zappy
- all commands for graphic protocol
- all commands for ai protocol

## **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
The binary needs command line arguments to correctly execute.

2023-06-16 15:27 UTC, Nioroe approved these changes
Seems good

2023-06-19 07:36 UTC, Sinan-Karakaya commented
@JasonLAGOUTE @thomasjuin1 Is this PR ready to merge?

2023-06-19 09:36 UTC, Sinan-Karakaya commented on zappy_server/include/map.h
> +    map_t *init_map(size_t x, size_t y);
need doc

2023-06-19 09:41 UTC, Sinan-Karakaya commented on zappy_server/src/free/free_zappy.c
> +// static void free_client_list(client_list_t *list)
Maybe remove commented functions

2023-06-19 09:42 UTC, Sinan-Karakaya requested changes
PLease fix my comments

2023-06-19 09:44 UTC, thomasjuin1 commented on zappy_server/src/free/free_zappy.c
> +// static void free_client_list(client_list_t *list)
In progress

2023-06-19 09:44 UTC, RoheeAxel approved these changes
Nice pr

2023-06-19 09:44 UTC, thomasjuin1 commented on zappy_server/include/map.h
> +    map_t *init_map(size_t x, size_t y);
done

2023-06-19 09:44 UTC, thomasjuin1 approved these changes
Code is fine, free in progress

2023-06-19 09:48 UTC, Sinan-Karakaya approved these changes
Looks good

2023-06-19 09:48 UTC, merged