GUI Animations
Sinan-Karakaya/Zappy pull request #25
Opened 2023-06-19 13:17 UTC by Nioroe

Add animations when aliens are incanting

2023-06-21 11:50 UTC, Sinan-Karakaya commented on zappy_gui/src/NetworkManager/NetworkManager.cpp
> +        newAlien = static_cast<zp::Alien *>(alien.get());
Do not use raw pointers

2023-06-21 11:50 UTC, Sinan-Karakaya requested changes
Fix raw pointers, replace by unique ptr

2023-06-23 07:39 UTC, thomasjuin1 approved these changes
Good animation 👍, love it

2023-06-23 12:08 UTC, Sinan-Karakaya approved these changes
looks good

2023-06-23 12:16 UTC, Sinan-Karakaya commented
DO NOT MERGE

PR might introduce memory leaks, testing in progress

2023-06-23 12:17 UTC, Sinan-Karakaya requested changes
Memory leak testing in progress

2023-06-23 12:32 UTC, Sinan-Karakaya approved these changes
Valgrind looks ok

2023-06-23 15:46 UTC, RoheeAxel approved these changes
Seem nice

2023-06-24 14:14 UTC, merged